export const REGISTRATION_CONFIRMED = 'registration confirmed'
export const REGISTRATION_FAILED = 'registration failed'
export const LOGIN_CONFIRMED = 'user login attempt successfull'
export const LOGIN_FAILED = 'user login attempt failed'
export const BUCKETS_FETCHED = 'buckets fetched'
export const BUCKET_SAVED = 'bucket saved'
